/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppAutomationsRouteImport } from './routes/_app.automations'
import { Route as AppInboxRouteImport } from './routes/_app.inbox'
import { Route as AppLogsRouteImport } from './routes/_app.logs'
import { Route as AppPostsRouteImport } from './routes/_app.posts'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppPostsIndexRouteImport } from './routes/_app.posts.index'
import { Route as AppPostsIdRouteImport } from './routes/_app.posts.$id'
import { Route as ApiAuthInstagramRouteImport } from './routes/api/auth/instagram'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiCronRefreshTokensRouteImport } from './routes/api/cron/refresh-tokens'
import { Route as ApiWebhooksInstagramRouteImport } from './routes/api/webhooks/instagram'
import { Route as ApiAuthInstagramCallbackRouteImport } from './routes/api/auth/instagram.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppPostsRoute = AppPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPostsIndexRoute = AppPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPostsRoute,
} as any)
const AppPostsIdRoute = AppPostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPostsRoute,
} as any)
const ApiAuthInstagramRoute = ApiAuthInstagramRouteImport.update({
  id: '/api/auth/instagram',
  path: '/api/auth/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRefreshTokensRoute = ApiCronRefreshTokensRouteImport.update({
  id: '/api/cron/refresh-tokens',
  path: '/api/cron/refresh-tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksInstagramRoute = ApiWebhooksInstagramRouteImport.update({
  id: '/api/webhooks/instagram',
  path: '/api/webhooks/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthInstagramCallbackRoute =
  ApiAuthInstagramCallbackRouteImport.update({
    id: '/callback',
    path: '/callback',
    getParentRoute: () => ApiAuthInstagramRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/data-deletion': typeof DataDeletionRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/automations': typeof AppAutomationsRoute
  '/inbox': typeof AppInboxRoute
  '/logs': typeof AppLogsRoute
  '/posts': typeof AppPostsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/posts/$id': typeof AppPostsIdRoute
  '/api/auth/instagram': typeof ApiAuthInstagramRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/cron/refresh-tokens': typeof ApiCronRefreshTokensRoute
  '/api/webhooks/instagram': typeof ApiWebhooksInstagramRoute
  '/posts/': typeof AppPostsIndexRoute
  '/api/auth/instagram/callback': typeof ApiAuthInstagramCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/data-deletion': typeof DataDeletionRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/automations': typeof AppAutomationsRoute
  '/inbox': typeof AppInboxRoute
  '/logs': typeof AppLogsRoute
  '/settings': typeof AppSettingsRoute
  '/posts/$id': typeof AppPostsIdRoute
  '/api/auth/instagram': typeof ApiAuthInstagramRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/cron/refresh-tokens': typeof ApiCronRefreshTokensRoute
  '/api/webhooks/instagram': typeof ApiWebhooksInstagramRoute
  '/posts': typeof AppPostsIndexRoute
  '/api/auth/instagram/callback': typeof ApiAuthInstagramCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/connect': typeof ConnectRoute
  '/data-deletion': typeof DataDeletionRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_app/automations': typeof AppAutomationsRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/posts': typeof AppPostsRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/posts/$id': typeof AppPostsIdRoute
  '/api/auth/instagram': typeof ApiAuthInstagramRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/cron/refresh-tokens': typeof ApiCronRefreshTokensRoute
  '/api/webhooks/instagram': typeof ApiWebhooksInstagramRoute
  '/_app/posts/': typeof AppPostsIndexRoute
  '/api/auth/instagram/callback': typeof ApiAuthInstagramCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/data-deletion'
    | '/privacy'
    | '/terms'
    | '/automations'
    | '/inbox'
    | '/logs'
    | '/posts'
    | '/settings'
    | '/posts/$id'
    | '/api/auth/instagram'
    | '/api/auth/logout'
    | '/api/cron/refresh-tokens'
    | '/api/webhooks/instagram'
    | '/posts/'
    | '/api/auth/instagram/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/data-deletion'
    | '/privacy'
    | '/terms'
    | '/automations'
    | '/inbox'
    | '/logs'
    | '/settings'
    | '/posts/$id'
    | '/api/auth/instagram'
    | '/api/auth/logout'
    | '/api/cron/refresh-tokens'
    | '/api/webhooks/instagram'
    | '/posts'
    | '/api/auth/instagram/callback'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/connect'
    | '/data-deletion'
    | '/privacy'
    | '/terms'
    | '/_app/automations'
    | '/_app/inbox'
    | '/_app/logs'
    | '/_app/posts'
    | '/_app/settings'
    | '/_app/posts/$id'
    | '/api/auth/instagram'
    | '/api/auth/logout'
    | '/api/cron/refresh-tokens'
    | '/api/webhooks/instagram'
    | '/_app/posts/'
    | '/api/auth/instagram/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ConnectRoute: typeof ConnectRoute
  DataDeletionRoute: typeof DataDeletionRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiAuthInstagramRoute: typeof ApiAuthInstagramRouteWithChildren
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiCronRefreshTokensRoute: typeof ApiCronRefreshTokensRoute
  ApiWebhooksInstagramRoute: typeof ApiWebhooksInstagramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/automations': {
      id: '/_app/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/posts': {
      id: '/_app/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AppPostsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/posts/': {
      id: '/_app/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof AppPostsIndexRouteImport
      parentRoute: typeof AppPostsRoute
    }
    '/_app/posts/$id': {
      id: '/_app/posts/$id'
      path: '/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof AppPostsIdRouteImport
      parentRoute: typeof AppPostsRoute
    }
    '/api/auth/instagram': {
      id: '/api/auth/instagram'
      path: '/api/auth/instagram'
      fullPath: '/api/auth/instagram'
      preLoaderRoute: typeof ApiAuthInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/refresh-tokens': {
      id: '/api/cron/refresh-tokens'
      path: '/api/cron/refresh-tokens'
      fullPath: '/api/cron/refresh-tokens'
      preLoaderRoute: typeof ApiCronRefreshTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/instagram': {
      id: '/api/webhooks/instagram'
      path: '/api/webhooks/instagram'
      fullPath: '/api/webhooks/instagram'
      preLoaderRoute: typeof ApiWebhooksInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/instagram/callback': {
      id: '/api/auth/instagram/callback'
      path: '/callback'
      fullPath: '/api/auth/instagram/callback'
      preLoaderRoute: typeof ApiAuthInstagramCallbackRouteImport
      parentRoute: typeof ApiAuthInstagramRoute
    }
  }
}

interface AppPostsRouteChildren {
  AppPostsIdRoute: typeof AppPostsIdRoute
  AppPostsIndexRoute: typeof AppPostsIndexRoute
}

const AppPostsRouteChildren: AppPostsRouteChildren = {
  AppPostsIdRoute: AppPostsIdRoute,
  AppPostsIndexRoute: AppPostsIndexRoute,
}

const AppPostsRouteWithChildren = AppPostsRoute._addFileChildren(
  AppPostsRouteChildren,
)

interface AppRouteChildren {
  AppAutomationsRoute: typeof AppAutomationsRoute
  AppInboxRoute: typeof AppInboxRoute
  AppLogsRoute: typeof AppLogsRoute
  AppPostsRoute: typeof AppPostsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAutomationsRoute: AppAutomationsRoute,
  AppInboxRoute: AppInboxRoute,
  AppLogsRoute: AppLogsRoute,
  AppPostsRoute: AppPostsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiAuthInstagramRouteChildren {
  ApiAuthInstagramCallbackRoute: typeof ApiAuthInstagramCallbackRoute
}

const ApiAuthInstagramRouteChildren: ApiAuthInstagramRouteChildren = {
  ApiAuthInstagramCallbackRoute: ApiAuthInstagramCallbackRoute,
}

const ApiAuthInstagramRouteWithChildren =
  ApiAuthInstagramRoute._addFileChildren(ApiAuthInstagramRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ConnectRoute: ConnectRoute,
  DataDeletionRoute: DataDeletionRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiAuthInstagramRoute: ApiAuthInstagramRouteWithChildren,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiCronRefreshTokensRoute: ApiCronRefreshTokensRoute,
  ApiWebhooksInstagramRoute: ApiWebhooksInstagramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
